/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package finalprojectoop;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author user
 */
public class Calculator extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        //Removed the border around the jinternalframe
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui = (BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
    }

    
    double num1,num2, result;
    String opr;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        sqr = new javax.swing.JButton();
        exponential = new javax.swing.JButton();
        sin = new javax.swing.JButton();
        cos = new javax.swing.JButton();
        tan = new javax.swing.JButton();
        raisey = new javax.swing.JButton();
        percent = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        tanh = new javax.swing.JButton();
        cosh = new javax.swing.JButton();
        sinh = new javax.swing.JButton();
        log = new javax.swing.JButton();
        overx = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        threebtn = new javax.swing.JButton();
        twobtn = new javax.swing.JButton();
        eightbtn = new javax.swing.JButton();
        fivebtn = new javax.swing.JButton();
        sixbtn = new javax.swing.JButton();
        ninebtn = new javax.swing.JButton();
        raise3 = new javax.swing.JButton();
        raise2 = new javax.swing.JButton();
        fourbtn = new javax.swing.JButton();
        sevenbtn = new javax.swing.JButton();
        onebtn = new javax.swing.JButton();
        factorial = new javax.swing.JButton();
        zerobtn = new javax.swing.JButton();
        negative = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        equals = new javax.swing.JButton();
        backspace = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 238, 204));

        jPanel2.setBackground(new java.awt.Color(0, 98, 65));

        input.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });

        sqr.setText("R");
        sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrActionPerformed(evt);
            }
        });

        exponential.setText("exp");
        exponential.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exponentialActionPerformed(evt);
            }
        });

        sin.setText("sin");
        sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinActionPerformed(evt);
            }
        });

        cos.setText("cos");
        cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cosActionPerformed(evt);
            }
        });

        tan.setText("tan");
        tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanActionPerformed(evt);
            }
        });

        raisey.setText("x^y");
        raisey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseyActionPerformed(evt);
            }
        });

        percent.setText("%");
        percent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentActionPerformed(evt);
            }
        });

        clear.setText("Clr");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        tanh.setText("tanh");
        tanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanhActionPerformed(evt);
            }
        });

        cosh.setText("cosh");
        cosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coshActionPerformed(evt);
            }
        });

        sinh.setText("sinh");
        sinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinhActionPerformed(evt);
            }
        });

        log.setText("log");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        overx.setText("1/x");
        overx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overxActionPerformed(evt);
            }
        });

        addition.setText("+");
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });

        minus.setText("-");
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        threebtn.setText("3");
        threebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threebtnActionPerformed(evt);
            }
        });

        twobtn.setText("2");
        twobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twobtnActionPerformed(evt);
            }
        });

        eightbtn.setText("8");
        eightbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightbtnActionPerformed(evt);
            }
        });

        fivebtn.setText("5");
        fivebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivebtnActionPerformed(evt);
            }
        });

        sixbtn.setText("6");
        sixbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixbtnActionPerformed(evt);
            }
        });

        ninebtn.setText("9");
        ninebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ninebtnActionPerformed(evt);
            }
        });

        raise3.setText("x^3");
        raise3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raise3ActionPerformed(evt);
            }
        });

        raise2.setText("x^2");
        raise2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raise2ActionPerformed(evt);
            }
        });

        fourbtn.setText("4");
        fourbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourbtnActionPerformed(evt);
            }
        });

        sevenbtn.setText("7");
        sevenbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenbtnActionPerformed(evt);
            }
        });

        onebtn.setText("1");
        onebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onebtnActionPerformed(evt);
            }
        });

        factorial.setText("n!");
        factorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorialActionPerformed(evt);
            }
        });

        zerobtn.setText("0");
        zerobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zerobtnActionPerformed(evt);
            }
        });

        negative.setText("+/-");
        negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negativeActionPerformed(evt);
            }
        });

        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        equals.setText("=");
        equals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsActionPerformed(evt);
            }
        });

        backspace.setText("B");
        backspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(zerobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(equals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(raisey, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(onebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(twobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(threebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(raise3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(raise2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fourbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(eightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ninebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(fivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sixbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(input, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exponential, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(overx, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exponential, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tanh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cosh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overx, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raisey, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(percent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addition, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(ninebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eightbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(fivebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sixbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(raise3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(raise2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fourbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(threebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(factorial, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zerobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equals, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(negative, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputActionPerformed

    private void sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the sqrt with Math.sqrt
        double t = Math.sqrt(Double.parseDouble(input.getText()));
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the sqrt value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_sqrActionPerformed

    private void exponentialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exponentialActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the exponential with Math.exp
        double t = Math.exp(Double.parseDouble(input.getText()));
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the exp value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_exponentialActionPerformed

    private void sinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the radians of the double value with Math.toRadians
        double s = Math.toRadians(Double.parseDouble(input.getText()));
        //Get the sin with Math.sin
        double t = Math.sin(s);
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the sin value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_sinActionPerformed

    private void cosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cosActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the radians of the double value with Math.toRadians
        double s = Math.toRadians(Double.parseDouble(input.getText()));
        //Get the cos with Math.cos
        double t = Math.cos(s);
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the cos value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_cosActionPerformed

    private void tanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the radians of the double value with Math.toRadians
        double s = Math.toRadians(Double.parseDouble(input.getText()));
        //Get the tan with Math.tan
        double t = Math.tan(s);
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the tan value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_tanActionPerformed

    private void raiseyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseyActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
        num1=Double.parseDouble(input.getText());
        
        //Set the text to blank
        input.setText("");
        
        //Set the opr(operation) to x^y
        opr = "x^y";
        
        
    }//GEN-LAST:event_raiseyActionPerformed

    private void percentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
         num1=Double.parseDouble(input.getText());
        
         //Set the text to blank
        input.setText("");
        
        //Set the opr(operation) to %(modulo)
        opr = "%";
    }//GEN-LAST:event_percentActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        //Set the text to blank
        input.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void tanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanhActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the tanh with Math.tanh(hyperbolic)
        
        double t = Math.tanh(Double.parseDouble(input.getText()));
        //Set the text to blank
        input.setText("");
         //Set the text to input + the tanh value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_tanhActionPerformed

    private void coshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coshActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the cosh with Math.cosh(hyperbolic)
        double t = Math.cosh(Double.parseDouble(input.getText()));
        //Set the text to blank
        input.setText("");
        //Set the text to input + the cosh value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_coshActionPerformed

    private void sinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinhActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the sinh with Math.sinh(hyperbolic)
        double t = Math.sinh(Double.parseDouble(input.getText()));
        //Set the text to blank
        input.setText("");
        //Set the text to input + the sinh value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_sinhActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the log with Math.log(logarithmic)
        double t = Math.log(Double.parseDouble(input.getText()));
        //Set the text to blank
        input.setText("");
        //Set the text to input + the log value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_logActionPerformed

    private void overxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overxActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Get the 1/x value
        double t = 1/(Double.parseDouble(input.getText()));
        
        //Set the text to blank
        input.setText("");
        //Set the text to input + the 1/x value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_overxActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
        num1=Double.parseDouble(input.getText());
        
        //Set the text to blank
        input.setText("");
        
        //Set the opr(operation) to +
        opr = "+";
        
        
        
    }//GEN-LAST:event_additionActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
         num1=Double.parseDouble(input.getText());
        //Set the text to blank
        input.setText("");
        //Set the opr(operation) to -
        opr = "-";
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
         num1=Double.parseDouble(input.getText());
        //Set the text to blank
        input.setText("");
        //Set the opr(operation) to *
        opr = "*";
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        //Change the text  into a double value with Double.parseDouble
        //Set the variable into num1
         num1=Double.parseDouble(input.getText());
        //Set the text to blank
        input.setText("");
        //Set the opr(operation) to /
        opr = "/";
    }//GEN-LAST:event_divideActionPerformed

    private void threebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threebtnActionPerformed
        // Set the text to "3" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"3");
    }//GEN-LAST:event_threebtnActionPerformed

    private void twobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twobtnActionPerformed
        // Set the text to "2" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"2");
    }//GEN-LAST:event_twobtnActionPerformed

    private void eightbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightbtnActionPerformed
        // Set the text to "8" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"8");
    }//GEN-LAST:event_eightbtnActionPerformed

    private void fivebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivebtnActionPerformed
        // Set the text to "5" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"5");
    }//GEN-LAST:event_fivebtnActionPerformed

    private void sixbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixbtnActionPerformed
        // Set the text to "6" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"6");
    }//GEN-LAST:event_sixbtnActionPerformed

    private void ninebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ninebtnActionPerformed
        // Set the text to "9" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"9");
    }//GEN-LAST:event_ninebtnActionPerformed

    private void raise3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raise3ActionPerformed
        //Change the text  into a double value with Double.parseDouble
        double t = Double.parseDouble(input.getText());
        //Formula for t raise to 3
        t=t*t*t;
        
         //Set the text to blank
        input.setText("");
        //Set the text to input + the t value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_raise3ActionPerformed

    private void raise2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raise2ActionPerformed
        //Change the text  into a double value with Double.parseDouble
        double t = Double.parseDouble(input.getText());
        
        //Formula for t raise to 2
        t=t*t;
        //Set the text to blank
        input.setText("");
        //Set the text to input + the t value
        input.setText(input.getText()+t);
    }//GEN-LAST:event_raise2ActionPerformed

    private void fourbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourbtnActionPerformed
        // Set the text to "4" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"4");
    }//GEN-LAST:event_fourbtnActionPerformed

    private void sevenbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenbtnActionPerformed
        // Set the text to "7" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"7");
    }//GEN-LAST:event_sevenbtnActionPerformed

    private void onebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onebtnActionPerformed
        // Set the text to "1" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"1");
    }//GEN-LAST:event_onebtnActionPerformed

    private void factorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorialActionPerformed
        //Change the text  into a double value with Double.parseDouble
        double t = Double.parseDouble(input.getText());
        
        double fact = 1;
        
        // Iterate from i = 1 to i = t, incrementing i by 1 each time (i++)
        for(int i=1; i<=t ;i++){
        
            // Multiply the factorial by every i from 1 to t
            fact = fact * i;
        
        }
         //Set the text to blank
        input.setText("");
        //Set the text to input + the fact value
        input.setText(input.getText()+fact);
    }//GEN-LAST:event_factorialActionPerformed

    private void zerobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zerobtnActionPerformed
        /// Set the text to "0" if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"0");
    }//GEN-LAST:event_zerobtnActionPerformed

    private void negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negativeActionPerformed
        // Set the text to "-"(negative) if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+"-");
    }//GEN-LAST:event_negativeActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        // Set the text to "." if there is no value in the input field; otherwise, combine the current text with the new number
        input.setText(input.getText()+".");
    }//GEN-LAST:event_dotActionPerformed

    private void equalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsActionPerformed
        //Change the text  into a double value with Double.parseDouble
        num2 = Double.parseDouble(input.getText());
        
        if(opr == "+"){
            // add num1 and num2 if opr is +
            result = num1 + num2;
            //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
        }else if(opr == "-"){
            // subtract num1 and num2 if opr is -
            result = num1 - num2;
             //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
        }else if(opr == "*"){
            // multiply num1 and num2 if opr is *
            result = num1 * num2;
            //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
        }else if(opr == "/"){
            // divide num1 and num2 if opr is /
            result = num1 / num2;
            //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
        }else if(opr == "%"){
            // Get the modulo of num1 and num2 if opr is %
            result = num1 % num2;
            //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
        }else if(opr == "x^y"){
            //Get the power of num1 and num2 if opr is x^y(num1 is the base and num2 is the exponent)
            result = Math.pow(num1, num2);
            //Change the value from double to string and set the text to result
            input.setText(Double.toString(result));
}
        
       

   
  
    }//GEN-LAST:event_equalsActionPerformed

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        
        String backSpace = null;
        
        // Check if Input Field is Not Empty
        if(input.getText().length()>0){
        // StringBuilder allows the Manipulation of string(input.getText())
        StringBuilder s = new StringBuilder(input.getText());
        
         // Delete Last Character
        s.deleteCharAt(input.getText().length()-1);
        
        // Convert StringBuilder to String
        backSpace = s.toString();
        
        // Set Text in Input Field
        input.setText(backSpace);
        }
    }//GEN-LAST:event_backspaceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addition;
    private javax.swing.JButton backspace;
    private javax.swing.JButton clear;
    private javax.swing.JButton cos;
    private javax.swing.JButton cosh;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eightbtn;
    private javax.swing.JButton equals;
    private javax.swing.JButton exponential;
    private javax.swing.JButton factorial;
    private javax.swing.JButton fivebtn;
    private javax.swing.JButton fourbtn;
    private javax.swing.JTextField input;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton log;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton negative;
    private javax.swing.JButton ninebtn;
    private javax.swing.JButton onebtn;
    private javax.swing.JButton overx;
    private javax.swing.JButton percent;
    private javax.swing.JButton raise2;
    private javax.swing.JButton raise3;
    private javax.swing.JButton raisey;
    private javax.swing.JButton sevenbtn;
    private javax.swing.JButton sin;
    private javax.swing.JButton sinh;
    private javax.swing.JButton sixbtn;
    private javax.swing.JButton sqr;
    private javax.swing.JButton tan;
    private javax.swing.JButton tanh;
    private javax.swing.JButton threebtn;
    private javax.swing.JButton twobtn;
    private javax.swing.JButton zerobtn;
    // End of variables declaration//GEN-END:variables
}
