/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalprojectoop;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;


public class Menu extends javax.swing.JFrame implements Runnable {
    // Instance variables for the home panel, thread, and time components
    Home home = new Home();
    Thread t = new Thread(this);
    private int hour, seconds, minutes;
    private String timestr;
    
   
    public Menu() {
        initComponents(); // Initialize components of the menu
        desktop.add(home).setVisible(true); // Add the home panel to the desktop pane and make it visible
        t.start(); // Start the clock thread
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jPanel1 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        pomodoroBtn = new javax.swing.JButton();
        converterBtn = new javax.swing.JButton();
        todolistBtn = new javax.swing.JButton();
        notepadBtn = new javax.swing.JButton();
        calendarBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 98, 65));

        homeBtn.setBackground(new java.awt.Color(0, 98, 65));
        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_menu_40px.png"))); // NOI18N
        homeBtn.setBorder(null);
        homeBtn.setContentAreaFilled(false);
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        pomodoroBtn.setBackground(new java.awt.Color(0, 98, 65));
        pomodoroBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Sand_Timer_40px.png"))); // NOI18N
        pomodoroBtn.setBorder(null);
        pomodoroBtn.setContentAreaFilled(false);
        pomodoroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pomodoroBtnActionPerformed(evt);
            }
        });

        converterBtn.setBackground(new java.awt.Color(0, 98, 65));
        converterBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_repeat_40px.png"))); // NOI18N
        converterBtn.setBorder(null);
        converterBtn.setContentAreaFilled(false);
        converterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterBtnActionPerformed(evt);
            }
        });

        todolistBtn.setBackground(new java.awt.Color(0, 98, 65));
        todolistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_list_40px.png"))); // NOI18N
        todolistBtn.setBorder(null);
        todolistBtn.setContentAreaFilled(false);
        todolistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todolistBtnActionPerformed(evt);
            }
        });

        notepadBtn.setBackground(new java.awt.Color(0, 98, 65));
        notepadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_notepad_40px.png"))); // NOI18N
        notepadBtn.setBorder(null);
        notepadBtn.setContentAreaFilled(false);
        notepadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notepadBtnActionPerformed(evt);
            }
        });

        calendarBtn.setBackground(new java.awt.Color(0, 98, 65));
        calendarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_calendar_40px.png"))); // NOI18N
        calendarBtn.setBorder(null);
        calendarBtn.setContentAreaFilled(false);
        calendarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calendarBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(0, 98, 65));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_logout_40px.png"))); // NOI18N
        logoutBtn.setBorder(null);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(converterBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(todolistBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addComponent(pomodoroBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notepadBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(calendarBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(converterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(todolistBtn)
                .addGap(18, 18, 18)
                .addComponent(pomodoroBtn)
                .addGap(18, 18, 18)
                .addComponent(notepadBtn)
                .addGap(18, 18, 18)
                .addComponent(calendarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(logoutBtn)
                .addGap(55, 55, 55))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 590));

        jPanel4.setBackground(new java.awt.Color(30, 57, 50));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Home");

        time.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 301, Short.MAX_VALUE)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Title)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        desktop.setBackground(new java.awt.Color(255, 238, 204));

        jPanel2.setBackground(new java.awt.Color(255, 238, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(770, 520));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        desktop.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 800, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
      
        
        desktop.removeAll(); // Remove all components from the desktop pane
        desktop.add(home).setVisible(true); // Add the home panel to the desktop pane and make it visible
        Title.setText("Home"); // Set the title text to "Home"

    }//GEN-LAST:event_homeBtnActionPerformed

    private void pomodoroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pomodoroBtnActionPerformed
      // TODO add your handling code here:
     Pomodorotimer timer = new Pomodorotimer(); // Create a new instance of the Pomodorotimer class

    desktop.removeAll(); // Remove all components from the desktop pane
    desktop.add(timer).setVisible(true); // Add the timer panel to the desktop pane and make it visible
    Title.setText("Pomodoro Timer"); // Set the title text to "Pomodoro Timer"

      
      
    }//GEN-LAST:event_pomodoroBtnActionPerformed

    private void converterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterBtnActionPerformed
        // TODO add your handling code here:
        Converter conv =  new Converter();// Create a new instance of the Converter class
        
        desktop.removeAll();// Remove all components from the desktop pane
        desktop.add(conv).setVisible(true);// Add the conv panel to the desktop pane and make it visible
        Title.setText("Converter");// Set the title text to "COnverter"
        
        
    }//GEN-LAST:event_converterBtnActionPerformed

    private void todolistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todolistBtnActionPerformed
        // TODO add your handling code here:
        TodoList todo =  new TodoList();// Create a new instance of the TodoList class
        
        desktop.removeAll();// Remove all components from the desktop pane
        desktop.add(todo).setVisible(true);// Add the conv panel to the desktop pane and make it visible
        Title.setText("ToDo List");// Set the title text to "ToDo List"
        
        
    }//GEN-LAST:event_todolistBtnActionPerformed

    private void notepadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notepadBtnActionPerformed
        // TODO add your handling code here:
        Notepad notepad =  new Notepad();// Create a new instance of the Notepad class
        
        desktop.removeAll();// Remove all components from the desktop pane
        desktop.add(notepad).setVisible(true);// Add the notepad panel to the desktop pane and make it visible
        Title.setText("Notepad");// Set the title text to "Notepad"
        
        
        
    }//GEN-LAST:event_notepadBtnActionPerformed

    private void calendarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calendarBtnActionPerformed
        // TODO add your handling code here:
        Calculator cal = new Calculator();// Create a new instance of the Calculator class
        
        desktop.removeAll();// Remove all components from the desktop pane
        desktop.add(cal).setVisible(true);// Add the cal panel to the desktop pane and make it visible
        Title.setText("Calculator");// Set the title text to "Calculator"
    }//GEN-LAST:event_calendarBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        Login login = new Login();// Create a new instance of the Login class
        dispose();// Remove all components from the jframe
        
        login.setVisible(true);//Make it visible
        
        
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton calendarBtn;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton converterBtn;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton homeBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton notepadBtn;
    private javax.swing.JButton pomodoroBtn;
    private javax.swing.JLabel time;
    private javax.swing.JButton todolistBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
// Start an infinite loop to continuously update the time
while (true) {
    // Get the current date and time
    Calendar c = Calendar.getInstance();
    // Get the hour of the day (0-23)
    hour = c.get(Calendar.HOUR_OF_DAY);
    // If the hour is greater than 12, subtract 12 to convert to 12-hour format
    if (hour > 12) {
        hour = hour - 12;
    }
    // Get the minute of the hour (0-59)
    minutes = c.get(Calendar.MINUTE);
    // Get the second of the minute (0-59)
    seconds = c.get(Calendar.SECOND);

    // Create a SimpleDateFormat object for formatting the time
    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm a");

    // Get the current date and time as a Date object
    Date dat = c.getTime();
    // Format the Date object as a string using the SimpleDateFormat
    timestr = sdf.format(dat);
    // Set the formatted time string to a GUI component named 'time'
    time.setText(timestr);
}

    }
}
